import 'package:get/get.dart';
import 'dart:io';
import '../services/realtime_db_service.dart';
import '../services/storage_service.dart';
import '../models/article_model.dart';

class ArticleController extends GetxController {
  final RealtimeDbService _dbService = RealtimeDbService();
  final StorageService _storageService = StorageService();
  
  final RxBool isLoading = false.obs;
  final RxList<ArticleModel> articles = <ArticleModel>[].obs;
  
  @override
  void onInit() {
    super.onInit();
    fetchArticles();
  }
  
  Future<void> fetchArticles() async {
    try {
      isLoading.value = true;
      final List<ArticleModel> fetchedArticles = await _dbService.getArticles();
      articles.value = fetchedArticles;
    } catch (e) {
      Get.snackbar('Error', 'Failed to load articles: ${e.toString()}');
    } finally {
      isLoading.value = false;
    }
  }
  
  Future<void> uploadArticle({
    required String title,
    required String content,
    required String category,
    required List<String> tags,
    required List<String> audience,
    File? image,
  }) async {
    try {
      isLoading.value = true;
      
      // Upload image to storage if provided
      String? imageUrl;
      if (image != null) {
        imageUrl = await _storageService.uploadArticleImage(image);
      }
      
      // Create article model
      final ArticleModel article = ArticleModel(
        id: '', // Will be generated by Firebase
        title: title,
        content: content,
        category: category,
        tags: tags,
        imageUrl: imageUrl,
        audience: audience,
        createdAt: DateTime.now(),
      );
      
      // Add to database
      await _dbService.addArticle(article);
      
      // Refresh articles list
      await fetchArticles();
      
      // Show success message
      Get.back(); // Close the upload screen
      Get.snackbar('Success', 'Article uploaded successfully');
    } catch (e) {
      Get.snackbar('Error', 'Failed to upload article: ${e.toString()}');
    } finally {
      isLoading.value = false;
    }
  }
  
  Future<void> deleteArticle(String articleId) async {
    try {
      isLoading.value = true;
      await _dbService.deleteArticle(articleId);
      await fetchArticles();
      Get.snackbar('Success', 'Article deleted successfully');
    } catch (e) {
      Get.snackbar('Error', 'Failed to delete article: ${e.toString()}');
    } finally {
      isLoading.value = false;
    }
  }
  
  List<ArticleModel> getArticlesByCategory(String category) {
    return articles.where((article) => article.category == category).toList();
  }
  
  List<ArticleModel> getArticlesByAudience(String audience) {
    return articles.where((article) => article.audience.contains(audience)).toList();
  }
  
  // Filter articles by both category and audience
  List<ArticleModel> filterArticles({
    String? category,
    String? audience,
    String? searchQuery,
  }) {
    return articles.where((article) {
      bool matchesCategory = category == null || article.category == category;
      bool matchesAudience = audience == null || article.audience.contains(audience);
      bool matchesSearch = searchQuery == null || searchQuery.isEmpty || 
                         article.title.toLowerCase().contains(searchQuery.toLowerCase()) ||
                         article.content.toLowerCase().contains(searchQuery.toLowerCase());
      
      return matchesCategory && matchesAudience && matchesSearch;
    }).toList();
  }
}